export default {
  // 栏目接口
  columnQuery: 'admin/column/query',
  columnAdd: 'admin/column/add',
  columnUpdate: 'admin/column/update',
  columnDelete: 'admin/column/delete',
  columnFetch: 'admin/column/fetch',
  // 单页接口
  pageQuery: 'admin/page/query',
  pageAdd: 'admin/page/add',
  pageUpdate: 'admin/page/update',
  pageDelete: 'admin/page/delete',
  pageFetch: 'admin/page/fetch',
  // 菜单接口
  navQuery: 'admin/nav/query',
  navAdd: 'admin/nav/add',
  navUpdate: 'admin/nav/update',
  navDelete: 'admin/nav/delete',
  navFetch: 'admin/nav/fetch',
  // 内容接口
  contentQuery: 'admin/content/query',
  contentAdd: 'admin/content/add',
  contentUpdata: 'admin/content/updata',
  contentDelete: 'admin/content/delete',
  contentFetch: 'admin/content/fetch',
  // 配置接口
  infoQuery: 'admin/info/query',
  infoAdd: 'admin/info/add',
  infoUpdate: 'admin/info/update',
  infoDelete: 'admin/info/delete',
  infoFetch: 'admin/info/fetch',
};
