export default {
  // 栏目接口
  columnQuery: 'admin/column/query',
  columnAdd: 'admin/column/add',
  columnUpdata: 'admin/column/updata',
  columnDelete: 'admin/column/delete',
  columnFetch: 'admin/column/fetch',
  // 单页接口
  pageQuery: 'admin/page/query',
  pageAdd: 'admin/page/add',
  pageUpdata: 'admin/page/updata',
  pageDelete: 'admin/page/delete',
  pageFetch: 'admin/page/fetch',
  // 菜单接口
  navQuery: 'admin/nav/query',
  navAdd: 'admin/nav/add',
  navUpdata: 'admin/nav/updata',
  navDelete: 'admin/nav/delete',
  navFetch: 'admin/nav/fetch',
  // 内容接口
  contentQuery: 'admin/content/query',
  contentAdd: 'admin/content/add',
  contentUpdata: 'admin/content/updata',
  contentDelete: 'admin/content/delete',
  contentFetch: 'admin/content/fetch',
  // 配置接口
  infoQuery: 'admin/info/query',
  infoAdd: 'admin/info/add',
  infoUpdata: 'admin/info/updata',
  infoDelete: 'admin/info/delete',
  infoFetch: 'admin/info/fetch',
};
